language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: "pip install -r requirements.txt"
script:
  - python -m pytest -m "not external_integration and not slow"
jobs:
  include:
    - stage: "Further tests"
      script: python -m pytest -m "external_integration"
      name: "External integration tests"
    - # stage name not required, will continue to use `test`
      script: python -m pytest -m "slow"
      name: "Slow tests"
